import { ProductItem } from '@/types';

export const MOCK_CATEGORIES = [
  {
    id: 'cat-1',
    name: 'Keyboards & Peripherals',
    slug: 'keyboards-peripherals',
    description: 'CNC Aluminum mechanical keyboards, optical switches, and ultra-lightweight mice.',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600',
    _count: { products: 2 },
  },
  {
    id: 'cat-2',
    name: 'Audiophile & Sound',
    slug: 'audiophile-sound',
    description: 'Planar magnetic headphones, high-resolution DACs, and studio reference monitors.',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
    _count: { products: 2 },
  },
  {
    id: 'cat-3',
    name: 'GPUs & Computing',
    slug: 'gpus-computing',
    description: 'Enthusiast graphics accelerators, custom cooling components, and compute hardware.',
    imageUrl: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600',
    _count: { products: 1 },
  },
  {
    id: 'cat-4',
    name: 'Monitors & Displays',
    slug: 'monitors-displays',
    description: 'Ultra-wide QD-OLED panels, calibrated color accuracy, and high refresh rates.',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600',
    _count: { products: 1 },
  },
];

export const MOCK_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-1',
    name: 'ApexPro 75% Custom Mechanical Keyboard',
    slug: 'apexpro-75-mechanical-keyboard',
    headline: 'CNC Gasket-Mounted Wireless Board with Hot-Swap Kailh Switches',
    description: 'Engineered from a single block of aerospace-grade aluminum. Features tri-mode wireless (2.4GHz / Bluetooth 5.3 / USB-C), per-key RGB, sound-dampening IXPE foam, and pre-lubed stabilizer bars.',
    price: 19999,
    originalPrice: 24999,
    stock: 7,
    rating: 4.9,
    reviewCount: 42,
    badge: 'LIMITED DROP',
    isFeatured: true,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Keyboards & Peripherals', slug: 'keyboards-peripherals' },
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800',
    ],
    specs: {
      'Case Material': 'CNC 6063 Anodized Aluminum',
      'Mounting Style': 'Gasket Mount with Poron Dampeners',
      'Connectivity': '2.4GHz Wireless, Bluetooth 5.3, USB-C',
      'Battery Life': 'Up to 240 Hours (RGB Off)',
      'Polling Rate': '1000Hz (Wireless & Wired)',
      'Weight': '1.75 kg',
    },
  },
  {
    id: 'prod-2',
    name: 'TitanRTX 4090 OC 24GB Liquid Ultra',
    slug: 'titanrtx-4090-liquid-ultra',
    headline: 'Extreme 4K/8K GPU with Integrated 360mm Closed-Loop Radiator',
    description: 'The pinnacle of graphical fidelity and neural rendering performance. Features 16,384 CUDA cores, 24GB of ultra-fast GDDR6X VRAM, and an integrated copper cold-plate liquid cooling system.',
    price: 169999,
    originalPrice: 189999,
    stock: 4,
    rating: 5.0,
    reviewCount: 19,
    badge: 'FLASH SALE',
    isFeatured: true,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    categoryId: 'cat-3',
    category: { id: 'cat-3', name: 'GPUs & Computing', slug: 'gpus-computing' },
    images: [
      'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800',
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800',
    ],
    specs: {
      'CUDA Cores': '16,384',
      'VRAM': '24GB GDDR6X (384-bit)',
      'Boost Clock': '2,670 MHz',
      'Cooling': 'AIO 360mm Aluminum Radiator + Triple ARGB Fans',
      'TDP': '450W (16-pin PCIe 5.0 12VHPWR)',
    },
  },
  {
    id: 'prod-3',
    name: 'QuantumFlow Studio Planar Headphones',
    slug: 'quantumflow-planar-headphones',
    headline: 'Open-Back Audiophile Monitors with Ultra-Thin Nanometer Diaphragms',
    description: 'Delivering unmatched acoustic clarity, wide soundstage, and sub-bass extension down to 10Hz. Handcrafted real walnut earcups and breathable lambskin memory foam headband.',
    price: 39999,
    originalPrice: 47999,
    stock: 9,
    rating: 4.8,
    reviewCount: 31,
    badge: 'TOP RATED',
    isFeatured: true,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    categoryId: 'cat-2',
    category: { id: 'cat-2', name: 'Audiophile & Sound', slug: 'audiophile-sound' },
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
    ],
    specs: {
      'Transducer Type': 'Planar Magnetic (100mm Diaphragm)',
      'Acoustic Design': 'Open-Back Studio Reference',
      'Frequency Response': '10 Hz – 50 kHz',
      'Impedance': '32 Ohms',
    },
  },
  {
    id: 'prod-4',
    name: 'VisionMaster 34" QD-OLED Curved Display',
    slug: 'visionmaster-34-qd-oled',
    headline: '1800R Quantum Dot OLED Gaming & Production Monitor (240Hz, 0.03ms)',
    description: 'Infinite contrast ratio with true blacks and 99.3% DCI-P3 cinematic color spectrum. Features USB-C 90W Power Delivery, integrated KVM switch, and custom graphene heatsink.',
    price: 84999,
    originalPrice: 99999,
    stock: 14,
    rating: 4.9,
    reviewCount: 68,
    badge: 'BESTSELLER',
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-4',
    category: { id: 'cat-4', name: 'Monitors & Displays', slug: 'monitors-displays' },
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800',
    ],
    specs: {
      'Screen Size': '34-inch Ultrawide (21:9)',
      'Resolution': '3440 x 1440 (UWQHD)',
      'Panel Type': 'QD-OLED',
      'Refresh Rate': '240 Hz',
    },
  },
  {
    id: 'prod-5',
    name: 'AeroGlide Carbon Precision Mouse',
    slug: 'aeroglide-carbon-mouse',
    headline: '39g Pure Carbon Fiber Shell with 8000Hz Optical Sensor',
    description: 'The world’s lightest high-rigidity carbon fiber gaming mouse. Zero flex, optical switches rated for 90 million clicks, and pure PTFE skate feet.',
    price: 11999,
    originalPrice: 14499,
    stock: 22,
    rating: 4.7,
    reviewCount: 54,
    badge: 'POPULAR',
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Keyboards & Peripherals', slug: 'keyboards-peripherals' },
    images: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800',
    ],
    specs: {
      'Weight': '39 grams',
      'Sensor': 'PixArt 3395 (30,000 DPI)',
      'Polling Rate': '8000 Hz',
    },
  },
  {
    id: 'prod-6',
    name: 'AcousticCore Pro Audio Interface',
    slug: 'acousticcore-pro-interface',
    headline: 'Dual-Channel XLR/TRS Preamp with 32-Bit Float 192kHz DAC',
    description: 'Ultra-low noise floor microphone preamps with +75dB of clean gain. Built-in hardware DSP compressor, equalizer, and real-time zero-latency headphone monitoring.',
    price: 24999,
    stock: 18,
    rating: 4.8,
    reviewCount: 23,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-2',
    category: { id: 'cat-2', name: 'Audiophile & Sound', slug: 'audiophile-sound' },
    images: [
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800',
    ],
    specs: {
      'Preamps': '2x Discrete Class-A (+75dB Gain)',
      'Conversion': '32-Bit Float / 192 kHz',
    },
  },
];
